### ISSUE TITLE
Loading animation on load video not show

### ISSUE THREAD

**Issue by softonica** [shiyiya/wordpress-plugin-oplayer#3]
I see in demo oplayer, if video loading show spiner animation but in wordpress spinner not showing

**Comment by shiyiya** [comment]
> I see in demo oplayer, if video loading show spiner animation but in wordpress spinner not showing

Can you give me the wordpress url?

**Comment by shiyiya** [comment]
![image](https://github.com/user-attachments/assets/b2b06a04-5565-43c3-9b10-e612672e609a)

**Comment by softonica** [comment]
https://gourl.my.id/watch/ookami-to-koushinryou-2024-episode-1/

**Comment by shiyiya** [comment]
![image](https://github.com/user-attachments/assets/eae8d11c-1bcd-43d9-8f44-b8a1d00059f9)

color is overrided

**Comment by softonica** [comment]
thank for your info i know, i can fix this

**Comment by shiyiya** [comment]
![image](https://github.com/user-attachments/assets/d9958a92-22dd-4f8b-b175-21f349fa43b1)
