### ISSUE TITLE
How to add subtitle

### ISSUE THREAD

**Issue by softonica** [shiyiya/wordpress-plugin-oplayer#4]
how to add subtitle in sortcode

**Comment by shiyiya** [comment]
check readme

[oplayer src="" poster="" subtitle="your-subtitle-link"]

**Comment by shiyiya** [comment]
Update to the latest version using subtitle. break change  

[oplayer src="" poster="" subtitle="your-subtitle-link"]

**Comment by softonica** [comment]
> Update to the latest version using subtitle. break change
> 
> [oplayer src="" poster="" subtitle="your-subtitle-link"]

not work

**Comment by shiyiya** [comment]
**Update to the latest version**
